# Generated by Django 2.2.3 on 2019-07-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, unique=True, verbose_name='Текст')),
                ('translation', models.CharField(blank=True, max_length=128, null=True, verbose_name='Перевод')),
                ('transcription', models.CharField(blank=True, max_length=128, null=True, verbose_name='Транскрипция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обнолвения')),
                ('first_letter', models.CharField(max_length=1, verbose_name='Первая буква слова')),
                ('number_of_letters', models.PositiveIntegerField(default=0, verbose_name='Количество букв')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='WordStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использовалось')),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата использвания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
