# Generated by Django 2.2.3 on 2019-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.CharField(default='', max_length=128, verbose_name='Slug'),
        ),
    ]
